extends Node

class_name WebsocketConstants

enum EnumActions {
	CREATE_ROOM,
	JOIN_ROOM,
	ROOM_CREATED,
	JOINED_ROOM,
	PLAYER_JOINED,
	ERROR,
	LEAVE_ROOM,
	PLAYER_LEFT,
	ROOM_DELETED,
	UPDATE_PLAYER_INFO,
	PLAYER_INFO_UPDATED,
	START_GAME,
	START_GAME_BROADCAST,
	UPDATE_PLAYER_POSITION,
	PLAYER_POSITION_UPDATED,
	DROP_BOMB,
	BOMB_DROPPED,
	EXPLODE_BOMB,
	BOMB_EXPLODED,
	CREATE_POWER_UP,
	POWER_UP_CREATED,
	REMOVE_POWER_UP,
	APPLY_POWER_UP,
	PLAYER_DIED,
	PLAYER_DIED_BROADCAST,
	GAME_OVER,
	CONNECT,
	TICK_STATE
}
